---
 out_dir: '../results/run_32/'
 dataset_dir: "./dataset/chembl28-cleaned.smi" 
 which_vocab: "selfies" # "selfies", "regex", or "char"
 vocab_path: "./vocab/chembl_selfies_vocab.yaml"
 percentage: 1

 rnn_config:
  # size of vocab + <eos> + <sos> + <pad> 
  # char: 47, regex:75, selfies:77
  num_embeddings: 77 
  embedding_dim: 128
  rnn_type: "GRU" # LSTM or GRU

  # rnn
  input_size: 128 # size of the recurrent neural network
  hidden_size: 512
  num_layers: 3
  dropout: 0

 batch_size: 512
 shuffle: True
 num_epoch: 10
 which_optimizer: adam
 learning_rate: 0.001
 weight_decay: 0.0001